using System.Globalization;
using System.Text;

namespace SIQS.PerformanceSpy;

/// <summary>Builds the disposable xUnit source captured by a performance-spy calibration.</summary>
internal static class PerformanceSpyTestSource
{
    public static string Generate(PerformanceSpyOptions options, IReadOnlyList<PerformanceCase> cases)
    {
        var builder = new StringBuilder();
        WritePreamble(builder, options);
        WriteCases(builder, cases);
        WriteTestBody(builder);
        return builder.ToString();
    }

    private static void WritePreamble(StringBuilder builder, PerformanceSpyOptions options)
    {
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// Disposable local performance spy baseline.");
        builder.AppendLine("// Regenerate before algorithmic tuning and delete when that tuning session is done.");
        builder.AppendLine($"// Generated at {DateTimeOffset.Now:O}.");
        builder.AppendLine();
        builder.AppendLine("using System.Diagnostics;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using SIQS.Contracts;");
        builder.AppendLine("using SIQS.Pipeline;");
        builder.AppendLine();
        builder.AppendLine("namespace SIQS.Pipeline.Tests;");
        builder.AppendLine();
        builder.AppendLine("public sealed class GeneratedPerformanceSpyTests");
        builder.AppendLine("{");
        builder.AppendLine($"    private const double RegressionTolerance = {options.RegressionTolerance.ToString("R", CultureInfo.InvariantCulture)};");
        builder.AppendLine("    private const double WarmupTolerance = 1.50;");
        builder.AppendLine();
        builder.AppendLine("    public static TheoryData<PerformanceCase> Cases => new()");
        builder.AppendLine("    {");
    }

    private static void WriteCases(StringBuilder builder, IReadOnlyList<PerformanceCase> cases)
    {
        foreach (var (testCase, caseIndex) in cases.Select((testCase, index) => (testCase, index)))
        {
            builder.Append("        new PerformanceCase(");
            builder.Append(testCase.Digits.ToString(CultureInfo.InvariantCulture));
            builder.Append(", ");
            builder.Append(testCase.BaselineAverageMilliseconds.ToString("R", CultureInfo.InvariantCulture));
            builder.Append(", ");
            builder.Append(caseIndex == 0 ? "true" : "false");
            builder.AppendLine(", new[]");
            builder.AppendLine("        {");
            foreach (var composite in testCase.Composites)
            {
                builder.Append("            \"");
                builder.Append(composite.ToString(CultureInfo.InvariantCulture));
                builder.AppendLine("\",");
            }

            builder.AppendLine("        }),");
        }

        builder.AppendLine("    };");
        builder.AppendLine();
    }

    private static void WriteTestBody(StringBuilder builder)
    {
        builder.Append("""
            [Theory]
            [MemberData(nameof(Cases))]
            public async Task Factors_digit_size_within_generated_baseline(PerformanceCase testCase)
            {
                var pipeline = new SiqsPipeline();
                var scratchRoot = Path.Combine(Path.GetTempPath(), "siqs-performance-spy", Guid.NewGuid().ToString("N"));
                Directory.CreateDirectory(scratchRoot);

                try
                {
                    GC.Collect();
                    GC.WaitForPendingFinalizers();
                    GC.Collect();

                    var stopwatch = Stopwatch.StartNew();
                    for (var i = 0; i < testCase.Composites.Length; i++)
                    {
                        var composite = BigInteger.Parse(testCase.Composites[i], CultureInfo.InvariantCulture);
                        var runDirectory = Path.Combine(scratchRoot, $"C{testCase.Digits}-{i:D4}");
                        var result = await pipeline.RunAsync(new FactorizationRequest(composite, RunDirectory: runDirectory), null, CancellationToken.None);
                        Assert.True(
                            result.Status is JobStatus.CompletedFactorFound or JobStatus.CompletedTrivialFactor && result.FactorFound,
                            $"C{testCase.Digits} composite {composite} was not factored: {result.ErrorSummary ?? result.Status.ToString()}.");
                    }
                    stopwatch.Stop();

                    var averageMilliseconds = stopwatch.Elapsed.TotalMilliseconds / testCase.Composites.Length;
                    var tolerance = testCase.Warmup ? WarmupTolerance : RegressionTolerance;
                    var allowedMilliseconds = testCase.BaselineAverageMilliseconds * tolerance;
                    Assert.True(
                        averageMilliseconds <= allowedMilliseconds,
                        $"C{testCase.Digits} averaged {averageMilliseconds:F3} ms/composite; generated baseline is {testCase.BaselineAverageMilliseconds:F3} ms/composite, tolerance allows {allowedMilliseconds:F3} ms/composite.");
                }
                finally
                {
                    if (Directory.Exists(scratchRoot))
                    {
                        Directory.Delete(scratchRoot, recursive: true);
                    }
                }
            }

            public sealed record PerformanceCase(int Digits, double BaselineAverageMilliseconds, bool Warmup, string[] Composites)
            {
                public override string ToString() => $"C{Digits}: {Composites.Length} composite(s), {BaselineAverageMilliseconds:F3} ms/composite";
            }
            }
        """);
    }
}
