<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SIQS.Contracts\SIQS.Contracts.csproj" />
    <ProjectReference Include="..\LinearAlgebra\LinearAlgebra.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>QS_LinAlg</RootNamespace>
    <AssemblyName>qs-linalg</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
