<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>SIQS.UI.Tests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SIQS.UI\SIQS.UI.csproj" />
    <ProjectReference Include="..\SIQS.Pipeline\SIQS.Pipeline.csproj" />
    <ProjectReference Include="..\SIQS.Overlord\SIQS.Overlord.csproj" />
  </ItemGroup>
</Project>
